# https://github.com/material-ocean/

# Default colors
[colors.primary]
background = '#0f111a'
foreground = '#d8dee9'

[colors.cursor]
cursor = '#ff4151'

[colors.normal]
black = '#4c566a'
red = '#bf616a'
green = '#a3be8c'
yellow = '#ebcb8b'
blue = '#81a1c1'
magenta = '#b48ead'
cyan = '#88c0d0'
white = '#e5e9f0'
