# Alacritty Theme — NordicPine
# Based on Gotham with a splash of Material_Oceanic and a bunch of modifications

# Default colors
[colors.primary]
background = '#0f111a'
foreground = '#c6e0df'

# Normal colors
[colors.normal]
black   = '#1c2030'  # black
red     = '#bb2938'  # red
green   = '#26a98b'  # green
yellow  = '#ddbc44'  # yellow
blue    = '#257994'  # blue
magenta = '#cca2c0'  # magenta
cyan    = '#33859d'  # cyan
white   = '#c6e0df'  # white

# Bright colors
[colors.bright]
black   = '#343b51'  # bright black
red     = '#e16c58'  # bright red
green   = '#38c9a7'  # bright green
yellow  = '#e6cc6f'  # bright yellow
blue    = '#087fab'  # bright blue
magenta = '#ffd2f8'  # bright magenta
cyan    = '#6ab4c2'  # bright cyan
white   = '#e4f5f4'  # bright white

[colors.selection]
background = '#232a3b'
foreground = '#e4f5f4'
