- defaults:
    link:
      relink: true
      create: true

- clean: ['~', '~/bin', '~/.config']

- clean:
  ~/:
    force: true
  ~/.config:
    recursive: true
  ~/.bin:
    recursive: true

- link:
    ~/.zshrc:
      path: zsh/zshrc.zsh
      force: true
    ~/.config/zsh/lib:
      path: zsh/lib
      force: true
    ~/.config/zsh/zfunctions:
      path: zsh/zfunctions
      force: true

    ~/.config/tmux/tmux.conf:
      path: config/tmux/tmux.conf
      force: true

    ~/.vimrc:
      path: config/vim/vimrc
    ~/.config/nvim:
      path: config/nvim
      force: true

    ~/.bashrc:
      path: bash/bashrc
      force: true

    ~/.config/ghostty:
      path: config/ghostty
      force: true

    ~/.config/alacritty:
      path: config/alacritty
      force: true

    ~/.config/sheldon:
      path: config/sheldon
      force: true

    ~/.config/starship.toml:
      path: config/starship/starship.toml

    ~/.config/bat/config:
      path: config/bat/config

    ~/bin:
      glob: true
      path: bin/*

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    -
     command: ./config/macos/setup-homebrew.sh
     description: Installing Homebrew and essential packages
     stdout: true
    -
     description: Downloading vim-plug to ~/.vim/autoload/plug.vim
     command: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
     stdout: true
