# Spaceship Prompt Config — remote/server variant
#
# Requires a nerd font

add_newline = true

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$helm\
$python\
$terraform\
$aws\
$env_var\
$custom\
$cmd_duration\
$line_break\
$jobs\
$time\
$status\
$shell\
$character"""

[aws]
symbol = " "
style = "bold #ddbc44"

[character]
success_symbol = "[❯](bold #087fab)[❯](bold #6ab4c2)[❯](bold #38c9a7)"
error_symbol = "[✖](bold #e16c58)[✖](bold #e16c58)[❯](bold #e16c58)"
vicmd_symbol ="[](bold #38c9a7)[❯](bold #087fab)"

[cmd_duration]
show_notifications = false
min_time_to_notify = 30_000

[directory]
truncation_length = 5
read_only = ""
read_only_style = "bold red"
home_symbol = " ~"
style = "#6ab4c2"

[directory.substitutions]
" ~/" = "~/"

[docker_context]
symbol = " "
style = "#257994"

[git_branch]
format = "[$symbol on $branch(:$remote_branch) ]($style)"
symbol = ""
style = "bold #38c9a7"

[git_metrics]
disabled = false
added_style = "bold #38c9a7"
deleted_style = "bold #e16c58"

[git_status]
style = "#c6e0df dimmed"
conflicted = ""
ahead = ""
behind = ""
diverged = "נּ"
untracked = ""
stashed = ""
modified = ""
staged = ""
renamed = ""
deleted = ""

[helm]
symbol = "ﴱ"
style = "#6ab4c2"

[hostname]
ssh_only = true
format = "[$ssh_symbol$hostname]($style) "
ssh_symbol = " "

[jobs]
symbol = " "
style = "bold #e16c58"

[kubernetes]
disabled = true

[python]
symbol = " "
style = "#38c9a7"

[terraform]
symbol = "TF  "
style = "#cca2c0"

[package]
disabled = true
