# Copy/selection colors
setw -g mode-style fg=#e4f5f4,bg=#232a3b

# Alert message line
set -g message-style fg=#c6e0df,bg=#343b51,bold
set -g message-command-style fg=#c6e0df,bg=#343b51

# Status line activity
setw -g window-status-activity-style fg=#c6e0df,bg=#343b51

# Pane borders
set -g pane-border-style fg=#257994,bg=#0f111a
set -g pane-active-border-style fg=#33859d,bg=#0f111a

# Statusline
set -g status on
set -g status-interval 1
set -g status-left-length 30
set -g status-left "#[fg=#0f111a,bg=#33859d,nobold]#[fg=#e4f5f4,bg=#33859d]  #S #[fg=#33859d,bg=#0f111a,nobold,noitalics,nounderscore]⫸ "
set -g status-right "#[fg=#38c9a7,bg=#0f111a,nobold,noitalics,nounderscore]◀#{prefix_highlight}#[fg=#38c9a7,bg=#0f111a,nobold,noitalics,nounderscore]◀#[fg=#33859d,bg=#0f111a,nobold,noitalics,nounderscore]#[fg=#e4f5f4,bg=#33859d]#(osascript -l JavaScript ~/.dotfiles/bin/tunes.js dark)#[fg=#33859d,bg=#0f111a,nobold,noitalics,nounderscore]#[fg=#e4f5f4,bg=#33859d] %b %d #[fg=#0f111a,bg=#33859d,nobold,noitalics,nounderscore]#[fg=#33859d,bg=#0f111a] #[fg=#087fab,bg=#0f111a,nobold,noitalics,nounderscore]#[fg=#e4f5f4,bg=#087fab] %R #[fg=#0f111a,bg=#087fab,nobold,noitalics,nounderscore]#[fg=#087fab,bg=#0f111a]#{online_status}"

set -g @online_icon "#[default]"

# tmux-prefix-highlight
set -g @prefix_highlight_fg '#0f111a'
set -g @prefix_highlight_bg '#38c9a7'
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_output_prefix ' '
set -g @prefix_highlight_output_suffix ' '
set -g @prefix_highlight_copy_mode_attr 'fg=#0f111a,bg=#38c9a7,bold'

set -g @offline_icon " #[fg=#ff5555,bg=#0f111a,nobold,noitalics,nounderscore]#[fg=#e4f5f4,bg=#ff5555,bold] 󰅛 OFFLINE #[fg=#0f111a,bg=#ff5555,nobold,noitalics,nounderscore]#[fg=#ff5555,bg=#0f111a]"

set -g status-right-length 150
set -g window-status-format "#[fg=#0f111a,bg=#343b51]#[fg=#c6e0df,bg=#343b51,nobold,noitalics,nounderscore] #I#[fg=#c6e0df,bg=#343b51,nobold,noitalics,nounderscore]❯ #[fg=#c6e0df,bg=#343b51]#W #[fg=#343b51,bg=#0f111a]"
set -g window-status-current-format "#[fg=#0f111a,bg=#33859d,nobold,noitalics,nounderscore] #[fg=#e4f5f4,bg=#33859d]#I#[fg=#e4f5f4,bg=#33859d,nobold,noitalics,nounderscore]❱ #[fg=#e4f5f4,bg=#33859d] #W #[fg=#33859d,bg=#0f111a,nobold,noitalics,nounderscore]"
set -g window-status-separator ""

# Window Titles
set -g set-titles on
set -g set-titles-string '[#I] #W'

# --- colors (NordicPine)
set -g status-style fg=#c6e0df,bg=#0f111a
setw -g window-status-style fg=#c6e0df
setw -g window-status-current-style fg=#e4f5f4,bg=#33859d
set -g display-panes-active-colour '#33859d'
set -g display-panes-colour '#1c2030'
setw -g clock-mode-colour '#33859d'

# Plugins that interpolate status-right must load here (after status-right is set)
run-shell ~/.config/tmux/plugins/tmux-prefix-highlight/prefix_highlight.tmux
run-shell ~/.config/tmux/plugins/tmux-online-status/online_status.tmux
